apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-journalforing
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka.pool }}
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-mellomlagring
      external:
        - host: {{ dokarkiv.ingress }}
  env:
    - name: DOKARKIV_INGRESS
      value: {{ dokarkiv.ingress }}