apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-journalforing
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 3
    max: 3
  resources:
    limits:
      memory: 6144Mi
    requests:
      cpu: 50m
      memory: 512Mi
  env:
    # Ganske unik minne tuning for denne appen. Den trenger mye minne i korte perioder.
    # 25% av 6144 = 1536Mi tilgjengelig for heap.
    # InitiatingHeapOccupancyPercent = 25% betyr at GC starter når 25% av heap er brukt.
    # 25% av 1536 = 384Mi. Det betyr at appen bør ligge på rundt 384Mi ved vanlig drift.
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:InitiatingHeapOccupancyPercent=25 -XX:MaxRAMPercentage=25.0 -XX:ActiveProcessorCount=4
    - name: DOKARKIV_INGRESS
      value: "{{ dokarkiv.ingress }}"
  secureLogs:
    enabled: true
  kafka:
    pool: "{{ kafka.pool }}"
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-mellomlagring
        - application: dp-soknad
      external:
        - host: "{{ dokarkiv.ingress }}"

