apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-journalforing
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 3
    max: 3
  resources:
    limits:
      memory: 2560Mi
    requests:
      cpu: 50m
      memory: 768Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka.pool }}
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-mellomlagring
        - application: dp-soknad
      external:
        - host: {{ dokarkiv.ingress }}
  env:
    - name: DOKARKIV_INGRESS
      value: {{ dokarkiv.ingress }}
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=25.0 -XX:ActiveProcessorCount=4 -XX:+PrintFlagsFinal

