package no.nav.dagpenger.behov.journalforing.tjenester

object DokumentTittelOppslag {

    fun hentTittel(brevkode: String) = brevkodeTilTittel[brevkode] ?: "Ukjent dokumentittel"

    private val brevkodeTilTittel = mapOf(
        "GENERELL_INNSENDING" to "Generell innsending",
        "K1" to "Dokumentasjon av andre ytelser",
        "M6" to "Timelister",
        "M7" to " Brev fra bobestyrer/konkursforvalter",
        "N2" to "Kopi av søknad",
        "N5" to "Kopi av undersøkelsesresultat",
        "N6" to "Annet",
        "NAV 04-01.03" to "Søknad om dagpenger (ikke permittert)",
        "NAV 04-01.04" to "Søknad om dagpenger ved permittering",
        "NAV 04-02.01" to "Søknad om utstedelse av attest PD U2",
        "NAV 04-02.03" to "Bekreftelse på ansettelsesforhold",
        "NAV 04-02.05" to "Søknad om attest PD U1/N-301 til bruk ved overføring av dagpengerettigheter",
        "NAV 04-03.07" to "Egenerklæring - overdragelse av lønnskrav",
        "NAV 04-03.08" to "Oversikt over arbeidstimer",
        "NAV 04-06.05" to "Søknad om godkjenning av utdanning med rett til dagpenger",
        "NAV 04-06.08" to "Søknad om dagpenger under etablering av egen virksomhet",
        "NAV 04-08.03" to "Bekreftelse på sluttårsak/nedsatt arbeidstid (ikke permittert)",
        "NAV 04-08.04" to "Bekreftelse på arbeidsforhold og permittering",
        "NAV 04-13.01" to "Egenerklæringsskjema for fastsettelse av grensearbeiderstatus",
        "NAV 04-16.03" to "Søknad om gjenopptak av dagpenger",
        "NAV 04-16.04" to "Søknad om gjenopptak av dagpenger ved permittering",
        "NAV 90-00.08" to "Klage og anke",
        "NAVe 04-01.03" to "Ettersendelse til søknad om dagpenger ved arbeidsledighet (ikke permittert)",
        "NAVe 04-01.04" to "Ettersendelse til søknad om dagpenger ved permittering",
        "NAVe 04-02.01" to "Ettersendelse til søknad om attest PD U2",
        "NAVe 04-02.05" to "Ettersendelse til søknad om attest PD U1/N-301 til bruk ved overføring av dagpengerettigheter",
        "NAVe 04-03.07" to "Ettersendelse til egenerklæring - overdragelse av lønnskrav ved konkurs mv",
        "NAVe 04-03.08" to "Ettersendelse til oversikt over arbeidstimer",
        "NAVe 04-06.05" to "Ettersendelse til søknad om godkjenning av utdanning med rett til dagpenger",
        "NAVe 04-06.08" to "Ettersendelse til søknad om dagpenger under etablering av egen virksomhet",
        "NAVe 04-08.03" to "Ettersendelse til bekreftelse på sluttårsak/nedsatt arbeidstid (ikke permittert)",
        "NAVe 04-08.04" to "Ettersendelse til bekreftelse på arbeidsforhold og permittering",
        "NAVe 04-16.03" to "Ettersendelse til søknad om gjenopptak av dagpenger (ikke permittert)",
        "NAVe 04-16.04" to "Ettersendelse til søknad om gjenopptak av dagpenger ved permittering",
        "O2" to "Arbeidsavtale",
        "O9" to "Bekreftelse fra studiested/skole",
        "S6" to "Dokumentasjon av sluttårsak",
        "S7" to "Kopi av arbeidsavtale/sluttårsak",
        "S8" to "Sjøfartsbok/hyreavregning",
        "T1" to "Elevdokumentasjon fra lærested",
        "T2" to "Dokumentasjon av sluttdato",
        "T3" to "Tjenestebevis",
        "T4" to "Oppholds- og arbeidstillatelse, eller registreringsbevis for EØS-borgere",
        "T5" to "SED U006 Familieinformasjon",
        "T6" to "Permitteringsvarsel",
        "T8" to "Dokumentasjon av arbeidsforhold",
        "T9" to "Dokumentasjon av helse og funksjonsnivå",
        "U1" to "U1 Perioder av betydning for retten til dagpenger",
        "V6" to "Kopi av sluttavtale",
        "X8" to "Fødselsattest/bostedsbevis for barn under 18 år",
        "Y2" to "Uttalelse eller vurdering fra kompetent fagpersonell"
    )
}
